# Development settings
#
# Various config files exposed on the host using volume mapping rather than
# Dockerfile ADD or COPY
version: '2'

services:
  php-fpm:
    build:
      context: ./php-fpm
      args:
        PHP_VERSION: ${PHP_VERSION}
        ALPINE_LINUX_VERSION: ${ALPINE_LINUX_VERSION}
    volumes:
      - ./application:/var/www
      # - ./php-fpm/etc:/usr/local/etc # try to copy before run to avoid extension not found error

  nginx:
    build:
      context: ./nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    volumes:
      - ./application:/var/www
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/sites:/etc/nginx/sites-available
      # - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - ${HTTP_PORT_MAPPING}
      - ${HTTPS_PORT_MAPPING}
    depends_on:
      - php-fpm

  mysql:
    build:
      context: ./mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    env_file:
      .env
